default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit, manual]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: end-of-file-fixer
          - id: check-case-conflict
          - id: check-symlinks
          - id: check-merge-conflict
            stages:
                - commit
                - merge-commit
                - manual
          - id: requirements-txt-fixer
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.13.0
      hooks:
          - id: commitlint
            additional_dependencies: ['@commitlint/config-conventional@19.0.3']
            pass_filenames: true
            stages:
                - commit-msg
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.3.4
      hooks:
        - id: ruff
          args: [ --fix ]
        - id: ruff-format
