[build-system]
requires = [
    "setuptools",
]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "TD", "FIX", "E501", "COM812", "ISC001", "PLR0913"]

[tool.ruff.lint.per-file-ignores]
"**/tests/**" = ["S101", "PLR2004"]
